name: Deploy to GCP

on:
  push:
    branches:
      - test-ci
env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  APPLICATION_CREDENTIALS: ${{ secrets.GCR_JSON_KEY }}

jobs:
  createRelease:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.FREESTAR_BOT_TOKEN }}
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - run: |
        echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
        cat ./package.json >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - run: |
        echo "VERSION=${{ fromJson(env.PACKAGE_JSON).version }}" >> $GITHUB_ENV

    - run: npm run rollup:min

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCR_JSON_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Upload Pubfig Files to GCP'
      run: gsutil cp dist/* gs://a.pub.network/core/videojs-ima/${{ env.VERSION }}
      
    - name: 'Set ACL for Pubfig Files'
      run: gsutil acl ch -r -u AllUsers:R gs://a.pub.network/core/videojs-ima/${{ env.VERSION }}
